---
apiVersion: v1
kind: Service
metadata:
  name: storage-mongo
  labels:
    name: storage-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  template:
      metadata:
        labels:
          role: mongo
      spec:
        terminationGracePeriodSeconds: 10
        containers:
          - name: mongo
            image: mongo
            ports:
              - containerPort: 27017
            volumeMounts:
              - name: mongo-persistent-storage
                mountPath: /data/db
#          - name: mongo-sidecar
#            image: cvallance/mongo-k8s-sidecar
#            env:
#              - name: MONGO_SIDECAR_POD_LABELS
#                value: "role=mongo"
          - name: mongo-express
            image: mongo-express:latest
            ports:
              - containerPort: 8081
            env:
              - name: ME_CONFIG_MONGODB_SERVER
                value: localhost
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "hdd"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi