kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-local-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi