---
apiVersion: v1
kind: Service
metadata:
  name: userdb
  labels:
    name: userdb
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-port
  - port: 8080
    targetPort: 8080
    name: sidecar-port
  clusterIP: None
  selector:
    role: mysql
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: userdb
spec:
  serviceName: "mysql"
  replicas: 1
  template:
      metadata:
        labels:
          role: mysql
      spec:
        volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-local-storage-claim
        terminationGracePeriodSeconds: 10
        containers:
          - name: mysql
            image: gcr.io/innate-life-217919/mysql:final
            ports:
              - containerPort: 3306
            volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
          - name: adminer
            image: adminer:4.7.0-standalone
            ports:
              - containerPort: 8080