---
apiVersion: v1
kind: Service
metadata:
  name: storage-mongo
  labels:
    name: storage-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo-port
  - port: 8081
    targetPort: 8081
    name: sidecar-port
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  template:
      metadata:
        labels:
          role: mongo
      spec:
        volumes:
          - name: mongo-persistent-storage
            persistentVolumeClaim:
              claimName: mongo-local-storage-claim
        terminationGracePeriodSeconds: 10
        containers:
#          - name: mongo-sidecar
#            image: cvallance/mongo-k8s-sidecar
#            env:
#              - name: MONGO_SIDECAR_POD_LABELS
#                value: "role=mongo"
          - name: mongo
            image: mongo
            ports:
              - containerPort: 27017
            volumeMounts:
              - name: mongo-persistent-storage
                mountPath: /data/db
          - name: mongo-express
            image: mongo-express:latest
            ports:
              - containerPort: 8081
            env:
              - name: ME_CONFIG_MONGODB_SERVER
                value: localhost