job:
  properties:
    api:
      templateUrl: https://www.alphavantage.co/query?apikey={apikey}&function={function}&symbol={symbol}&interval={interval}
      key: LEP0XRATU8LATEQ7
      symbols:
        - MSFT
        - AAPL
        - BA
        - BABA
      interval: 1min
      function: TIME_SERIES_INTRADAY
      outputsize: compact
server:
  port: 8888

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  batch:
    job:
      enabled: false
  application:
    name: financial-job

---

spring:
  profiles: dev
job:
  properties:
    cron: 0 0/4 * * * ?
    threads: 1
services:
  list:
    -
      name: storage-service
      resolution: LOCAL
      port: 8889
      version: 0.1
financial-domain:
  security:
    jwt-props:
      jwtSecret: DEV_SECRET
    systemToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJTWVNURU0iLCJuYW1lIjoic3lzdGVtIiwicGVybWlzc2lvbnMiOlsiYWRtaW5fcGVybWlzc2lvbiJdLCJpYXQiOjE1NDUxMjU0NTQsImV4cCI6OTk0NTIxMTgyOX0.gFWogYCpup_qxM1Z7pa_4cVEJQBpHDoMyScMwQWI7lCi7jr4AMdK5_0YSDhYvO2EQVNt9jxJ6G_37yBP2ah0fw

---

spring:
  profiles: stage
job:
  properties:
    cron: 0 0 12 * * *
    threads: 4
services:
  list:
    -
      name: storage-service
      resolution: CLUSTER
      port: 8889
      version: 0.1
financial-domain:
  security:
    jwtProps:
      jwtSecret: ${JWT_SECRET}
    systemToken: ${SYSTEM_JWT_TOKEN}