job:
  properties:
    api:
      templateUrl: https://www.alphavantage.co/query?apikey={apikey}&function={function}&symbol={symbol}&interval={interval}
      key: LEP0XRATU8LATEQ7
      symbols:
        - MSFT
        - AAPL
        - BA
        - BABA
      interval: 1min
      function: TIME_SERIES_INTRADAY
      outputsize: compact
server:
  port: 8888

financialDomain:
  enableDiscovery: false

spring:
  batch:
    job:
      enabled: false

---

spring:
  profiles: dev
job:
  properties:
    cron: 0 0/1 * * * ?
    threads: 1
services:
  list:
    -
      name: storage
      resolution: LOCAL
      port: 8889
      version: 0.1
    -
      name: ui
      resolution: LOCAL
      port: 8890
      version: 0.1

---

spring:
  profiles: stage
job:
  properties:
    cron: 0 0 12 * * *
    threads: 4