spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8991

jdbc:
  connectionPool: 10

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:tcp://${DEV_HOST_ADDRESS:localhost}/~/userDB
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

financial-domain:
  security:
    jwt-props:
      jwtSecret: DEV_SECRET
    systemToken: token

---

spring:
  profiles: stage
  datasource:
      url: jdbc:h2:tcp://userdb/~/userDB
      username: ${USER_DB_USERNAME}
      password: ${USER_DB_PASSWORD}
      driver-class-name: org.h2.Driver
financial-domain:
  security:
    jwtProps:
      jwtSecret: ${JWT_SECRET}
    systemToken: ${SYSTEM_JWT_TOKEN}

---