---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  labels:
    app: authorization-service
    monitoring: prometheus
spec:
  type: ClusterIP
  selector:
    app: authorization-service
  ports:
  - protocol: TCP
    port: 8992
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-service-deployment
  labels:
    app: authorization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  template:
    metadata:
      labels:
        app: authorization-service
    spec:
      containers:
        - name: authorization-service
          image: gcr.io/innate-life-217919/authorization-server:0.0.1-SNAPSHOT
          env:
            - name: DEBUG_AGENT
              value: ""
            - name: JWT_EXPIRES_IN
              value: "86400"
            - name: PASSWORD_HASH_STERNGTH
              value: "10"
          envFrom:
            - configMapRef:
                name: profile-config
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: system-token-secret
          ports:
            - containerPort: 8992
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8992
            initialDelaySeconds: 15
            periodSeconds: 5