---
apiVersion: v1
kind: Service
metadata:
  name: financial-job-service
  labels:
    app: financial-job-service
spec:
  type: ClusterIP
  selector:
    app: financial-job
  ports:
  - protocol: TCP
    port: 8888
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-job-deployment
  labels:
    app: financial-job
spec:
  selector:
    matchLabels:
      app: financial-job
  template:
    metadata:
      labels:
        app: financial-job
    spec:
      containers:
        - name: financial-job
          image: gcr.io/innate-life-217919/financial-job:0.0.1-SNAPSHOT
          env:
            - name: DEBUG_AGENT
              value: ""
            - name: JOB_CRON_SCHEDULE
              value: 0 0/10 * * * ?
          envFrom:
            - configMapRef:
                name: profile-config
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: system-token-secret
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 5