---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
  labels:
    app: storage-service
spec:
  type: ClusterIP
  selector:
    app: storage-service
  ports:
  - protocol: TCP
    port: 8889
    #Dev setup
    #nodePort: 32142
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service-deployment
  labels:
    app: storage-service
spec:
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
        - name: storage-service
          image: gcr.io/innate-life-217919/storage-service:0.0.1-SNAPSHOT
          env:
            - name: DEBUG_AGENT
              value: ""
          envFrom:
            - configMapRef:
                name: profile-config
            - secretRef:
                name: jwt-secret
          ports:
            - containerPort: 8889
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8889
            initialDelaySeconds: 15
            periodSeconds: 5