---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 8991
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: gcr.io/innate-life-217919/user-service:0.0.1-SNAPSHOT
          env:
            - name: DEBUG_AGENT
              value: ""
          envFrom:
            - configMapRef:
                name: profile-config
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: mysql-credentials-secret
            - secretRef:
                name: system-token-secret
          ports:
            - containerPort: 8991
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8991
            initialDelaySeconds: 15
            periodSeconds: 5