version: '2'
services:
  storage-mongo:
    image: mongo:latest
    container_name: storage-mongo
    ports:
      - 27017:27017
    volumes:
      - financial-data:/data/db
  mongo-express:
        restart: always
        depends_on:
          - storage-mongo
        image: mongo-express:latest
        ports:
          - 8081:8081
        links:
          - storage-mongo:mongo
volumes:
  financial-data:
