spring:
  profiles:
    active: dev
  application:
    name: authorization-server

server:
  port: 8992

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: dev
services:
  list:
    -
      name: user-service
      resolution: LOCAL
      port: 8991
      version: 0.1
financial-domain:
  security:
    jwt-props:
      expiresIn: 86400
      jwtSecret: DEV_SECRET
    #Not used now
    passwordHashingStrength: 10
    systemToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJTWVNURU0iLCJuYW1lIjoic3lzdGVtIiwicGVybWlzc2lvbnMiOlsiYWRtaW5fcGVybWlzc2lvbiJdLCJpYXQiOjE1NDUxMjU0NTQsImV4cCI6OTk0NTIxMTgyOX0.gFWogYCpup_qxM1Z7pa_4cVEJQBpHDoMyScMwQWI7lCi7jr4AMdK5_0YSDhYvO2EQVNt9jxJ6G_37yBP2ah0fw

---

spring:
  profiles: stage
services:
  list:
    -
      name: user-service
      resolution: CLUSTER
      port: 8991
      version: 0.1
financial-domain:
  security:
    jwt-props:
      jwtSecret: ${JWT_SECRET}
      expiresIn: ${JWT_EXPIRES_IN}
    #Not used now
    passwordHashingStrength: ${PASSWORD_HASH_STERNGTH}
    systemToken: ${SYSTEM_JWT_TOKEN}

---