spring:
  profiles:
    active: dev

jdbc:
  connectionPool: 10
server:
  port: 8992


---

spring:
  profiles: dev
services:
  list:
    -
      name: user-service
      resolution: LOCAL
      port: 8991
      version: 0.1
financial-domain:
  security:
    expiresIn: 86400
    jwtSecret: DEV_SECRET
    #Not used now
    passwordHashingStrength: 10

---

spring:
  profiles: stage
services:
  list:
    -
      name: user-service
      resolution: CLUSTER
      port: 8991
      version: 0.1
financial-domain:
  security:
    jwtSecret: ${JWT_SECRET}
    expiresIn: ${JWT_EXPIRES_IN}
    #Not used now
    passwordHashingStrength: ${PASSWORD_HASH_STERNGTH}
