server:
  port: 8889
spring:
  application:
    name: storage-service

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
financial-domain:
  security:
    jwt-props:
      jwtSecret: DEV_SECRET

---

spring:
  profiles: stage
  data:
      mongodb:
        uri: mongodb://storage-mongo:27017/db
financial-domain:
  security:
    jwtProps:
      jwtSecret: ${JWT_SECRET}