---
apiVersion: v1
kind: Service
metadata:
  name: service-prometheus
  labels:
    prometheus: service-prometheus
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    port: 9090
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          volumeMounts:
            - name: scrape-configs
              mountPath: /etc/prometheus
          ports:
            - containerPort: 9090
      volumes:
        - name: scrape-configs
          configMap:
            name: prometheus-scrape-config